// <auto-generated />
namespace ASP.NETWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dataAnnotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dataAnnotations));
        
        string IMigrationMetadata.Id
        {
            get { return "202110060502448_dataAnnotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
